### ISSUE TITLE
documentation needed

### ISSUE THREAD

**Issue by septor** [bunnybattalion/steam-activated-mechanoid#1]
The bot's code was ripped form a personal bot, so documentation does not exist. This will be the first thing I address before anything else gets added or changed.

**Comment by lhoste** [comment]
Hey, i full fill the config.json file and put it in the directory. after running node.js i got some  lines in the terminal loading some modules and one big error on the last. Do you have an idea of what it is ? 

![capture d ecran 2018-06-19 a 00 42 06](https://user-images.githubusercontent.com/32936441/41565998-aedc2124-7359-11e8-8593-09961434db59.png)

**Comment by septor** [comment]
Says "incorrect logins details provided". You need to make sure your token is correct.
